name: Deploy Wazuh Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Ansible
        run: |
          cd ansible
          ansible-playbook -i inventories/production playbooks/deploy.yml
