name: Wazuh CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-scan-test:
    name: Build, Scan, Test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images (if custom Dockerfiles exist)
        run: |
          docker build -t your-registry/wazuh-indexer:$(git rev-parse --short HEAD) ./docker/wazuh-indexer
          # Add other images if needed

      - name: Run Trivy vulnerability scanner
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH your-registry/wazuh-indexer:$(git rev-parse --short HEAD)
        # The pipeline will fail if critical/high vulnerabilities are found

      - name: Run Ansible playbook for deployment (on push to main)
        if: github.ref == 'refs/heads/main' && success()
        run: |
          cd ansible
          echo "${{ secrets.VAULT_PASSWORD }}" > vault_pass.txt
          ansible-playbook -i inventories/production playbooks/deploy.yml --vault-password-file vault_pass.txt
          rm vault_pass.txt
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }} # This makes the variable available to the shell

  selenium-test:
    name: Selenium Test
    runs-on: self-hosted
    needs: build-scan-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Selenium tests
        run: |
          pip3 install -r tests/selenium/requirements.txt
          python3 tests/selenium/test_dashboard.py
        env:
          DASHBOARD_URL: https://localhost
          ADMIN_USER: ${{ secrets.WAZUH_ADMIN_USER }}
          ADMIN_PASS: ${{ secrets.WAZUH_ADMIN_PASS }}
